---
title: "02-analysis"
format: html
---

# Introduction

 In the following notebook I will compare the weather at stadiums on match days.
 
# Libraries

```{r}
# Installing packages
library(tidyverse)
library(lubridate)
```


# Loading data

```{r}
spring_schedule_2025 <- read_csv("data-processed/exact_2025_weather_spring_sched.csv")
summer_schedule_2025 <- read_csv("data-processed/exact_2025_weather_summer_sched.csv")
early_kickoff_schedule_spring <- read_csv("data-processed/weekly_schedule_early_spring.csv")
early_kickoff_schedule_summer <- read_csv("data-processed/weekly_schedule_early_summer.csv")
late_kickoff_schedule_spring <- read_csv("data-processed/weekly_schedule_late_spring.csv")
late_kickoff_schedule_summer <- read_csv("data-processed/weekly_schedule_late_summer.csv")
```

```{r}
spring_schedule_2025 |> filter(Team == "Atlanta United FC") |> 
```



# Count viz

## Making a dataframe with the counts of matchdays ovre 30 degrees

```{r}

spring_over_thirty_count <- early_kickoff_schedule_spring |> 
  mutate(week_year = isoweek(true_date)) |>
  group_by(Team, week_year) |> 
  summarise(avg_temp = mean(feelslike)) |> 
  filter(avg_temp >= 32) |>
  ungroup() |> 
  group_by(Team) |> 
  count() |> 
  ungroup()

summer_over_thirty_count <- early_kickoff_schedule_summer |> 
  mutate(week_year = isoweek(true_date)) |>
  group_by(Team, week_year) |> 
  summarise(avg_temp = mean(feelslike)) |> 
  filter(avg_temp >= 32) |>
  ungroup() |> 
  group_by(Team) |> 
  count() |> 
  ungroup()



spring_under_freezing_count <- early_kickoff_schedule_spring |> 
  mutate(week_year = isoweek(true_date)) |>
  group_by(Team, week_year) |> 
  summarise(avg_temp = mean(feelslike)) |> 
  filter(avg_temp <= 0) |>
  ungroup() |> 
  group_by(Team) |> 
  count() |> 
  ungroup()



summer_under_freezing_count <- early_kickoff_schedule_summer |> 
  mutate(week_year = isoweek(true_date)) |>
  group_by(Team, week_year) |> 
  summarise(avg_temp = mean(feelslike)) |> 
  filter(avg_temp <= 0) |>
  ungroup() |> 
  group_by(Team) |> 
  count() |> 
  ungroup()

missing_teams <- summer_under_freezing_count |>
  filter(!Team %in% spring_under_freezing_count$Team) |>
  mutate(n = 0)

spring_under_freezing_count <- bind_rows(spring_under_freezing_count, missing_teams)

```


## Making the Viz

```{r}
summer_over_thirty_count |> mutate(difference_n = spring_over_thirty_count$n-summer_over_thirty_count$n) |> 
  filter(difference_n != 0) |> 
  ggplot(aes(x = difference_n, y = fct_reorder(Team, difference_n))) +
  geom_col() +
  scale_y_discrete(name = NULL) +
  scale_x_continuous(name = NULL)

summer_under_freezing_count |> mutate(difference_n = spring_under_freezing_count$n-summer_under_freezing_count$n) |> 
  ggplot(aes(x = difference_n, y = fct_reorder(Team, difference_n))) +
  geom_col() +
  scale_y_discrete(name = NULL) +
  scale_x_continuous(name = NULL, limits = c(-20,5), breaks = seq(-20,5,5))
```

# Viz for direct season to season difference

## Function to summarize hourly data to daily

```{r}
# Converts empty precipitation values to 0, removes an empty observation
hourly_to_daily <- function(dataframe){
  #Cleaning the date, creating a day column, and converting NA to 0.
  no_na_dataframe <- dataframe |> mutate(date = as.Date(datetime), precipitation = if_else(is.na(dataframe$precip), 0, dataframe$precip),snow = if_else(is.na(dataframe$snow), 0, dataframe$snow), week = isoweek(date))
  #Finding the high temp, low temp and precipitation for each day.
  dataframe_clean <- no_na_dataframe |>  
  group_by(Team, date) |> 
  summarise(temp = mean(temp, na.rm = TRUE),
            feelslike = mean(feelslike, na.rm = TRUE),
            precipitation = sum(precip),
            snow = sum(snow),
            week = week) |> 
  group_by(Team, week) |> 
  summarise(temp = mean(temp, na.rm = TRUE),
            feelslike = mean(feelslike, na.rm = TRUE),
            precipitation = sum(precipitation),
            snow = sum(snow))  

  
  return(dataframe_clean)
}
```

## Saving the 2025 season weather data as a summary

```{r}
summarized_spring_sched_2025 <- hourly_to_daily(spring_schedule_2025)
summarized_summer_sched_2025 <- hourly_to_daily(summer_schedule_2025)
```

```{r}
make_plot <- function(team){
  summarized_spring_sched_2025 |> 
    filter(.data$Team == .env$team) |> 
    ggplot() +
    aes(x = week, y = Team, fill = feelslike) +
    geom_tile(width = 0.95, height = 0.95) + 
    coord_fixed(expand = FALSE) +
    theme_classic() +
    scale_x_continuous(breaks = seq(0,50,5)) +
    scale_fill_viridis_c(option = "B", begin = 0.15)
}
```

```{r}
make_plot("Atlanta United FC")
```

